local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi(data) m=string.sub(data, 0, 200) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


while _G.Autokg do

local Event = game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('hsNJVmnOHxioSHdsxBHcgvliqomuPgjuFrYpaVxPQsINjTohYyAOmltNVDYISxNFwwFwdJzhYJzPCZzqGgnANWdxyoGoQVvSAMZchNuoGgOVfJhUlSkutzbGLiEYPpdsOswMBniOIHvFsHxZJYsAIuMjANgyboGNOGokluwhXLBckikKOXKFeajrXczwAZyftwGPkZSUUGxheWVycw==')).LocalPlayer.startevent
Event:FireServer(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('YwqgcrjefoJVkEozXKtAvCZpJgGBWmWJmbAKmFhpzoCJwGpRAhOZDFRMHkMAnmUrxhsJESQYmPgoOnhMPouPeVGKzkEeqNLsfCbJpNDxdbZfAhWQaEXbrvHPYQGsKwtCKBZmoPXWTTkYKwoDWAhtLLAhnaaPZyKMysVYdFBGkrFdvpvQgmaJLhjoTQNYWxdkkiqHdLfSc3Bpbg=='), VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('UeoKEsdiQadZVKWixuoJtkmABELTaLVEhwhbMUkNYPNbfkrSTDKtKAWAgvZynSlDDYQORAVNnFSprEBoXBYolbqLQwdXDwwtLUBSUbYaBAvyAOEFBJblRnSCpuiOfAeLpRPOokMprfCQsXoLaIaWgxYyVirJIGDZNocAyahOXKWvTtjZmxpzbRFsiabedvRQROKbuQEUa2cx'))
 wait(0.2)
local Event = game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('cJcVUtfwxyKRKVJqQPbfCQRPtwcKOdEkSIHNvBibxilydbBMOekKRpmTRrvXMYTEnnZPRKqaakKdJeMHizIcINBfnraEYYrrOFtjNzgdyaLaSefISSBMJWEJrcAUJpFaZrPqZTffbiaAwaZRFkNmJHVWHycHPibhmUwZOUFhidTgtggakfnugnvvEqIDDggIZcXngVwDUGxheWVycw==')).LocalPlayer.startevent
Event:FireServer(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('PyCSrIzyOzmRVKYJjHPlizhvtiZPbPKxnieaGBUYlqSwZTEbyTHbJpQiNOohaDTYCsKrEVCYSkfzPHhgCrLrePCszEFxuzporWNuNqXSKEcDMUwvJZcqievlLccPORWIoadBaLdSaGAgANLQwvccRuytZWLZvZBqudPUkjAMBbTuWqgxFuENMalIKyEKEhElampezuqUc3Bpbg=='), VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('HSpaeayfSnvRHoOKeKqlNoDCziNtMcJnpyQUeJsOVyLqYGPHzuFZYwLIhFvuewrrxYFjSjnnIiotZzfVnBwuefEWKtCtOvjbhyEotyGiemNcTGHPmWHanpUVhqSvUlyukXMCTesvKrbPnvLTjWLCLWfUbIMNliNfDQEoKqlFocsPFaHNNGELwxXShMPCehhuHQcQtCkPa2cy'))
 wait(0.2)
local Event = game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('rfviAJMzagEFIZnBjiEYbxmtJRYnFjxebozvyKPRGpMowpHixjwuFjqsZhuczWmkfKrhUbgQxBAonoGEEqWyNVCFUHDQflYKTAdCjJqsJlmTnPbJkzVziOLkJiaZyaOVGSlTgPQUperhjOmBLXAIsLyQJdtFsitpNZimHCQacYKWASozhGAhgoJqoxtJRUVLyjbHIxAKUGxheWVycw==')).LocalPlayer.startevent
Event:FireServer(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('AYPJyIdugLCkrOyrVPtVyUTvCEJcdPqGEfqgUqkluztfXLWfSHGQYFKoflIimyakiWUuRyFbvmpqiFouoxKRDyfYKtLIQkYgyGSgAUEfisaSwOvLwvYsoclRIdpoueKmoyAAerefsCyKJlVqwzZgzgkGDAOelNyYFQrAWJtBYObKlnDZyWBlCPMpuMAZEVMFUtQkPImfc3Bpbg=='), VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('OevmgmmLRVLoVFmDwOaFCFDVoinmkhzVLonRtXzcAyVwcEPNdgrKPYelJlGbfJJObWkFcYlsMDImzFGCwbOLBwcHubVXerFyZtZfUeNvTHKwDOKtRCcatjhjgGBdNxqGIyhtTgneGwkkTqnAOCLbPDfRZTlxNwMJnAWhmkNGVttggnPaEBoRPsvZMeFZYyXnnSuNTwAsa2cz'))
 wait(0.2)
local Event = game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('qVchXHwRwMXzKnrYjlZLKwQtquNscljVPUCdlnZVQddKxnLDOsqLNFyNJOPlwlBHyVuWMeldSIQCddfAHsCFwHQGYcllyHhOorZIXhArOgeJZUtuDozKmTxcQhZritBLzbBkxoLsqKhEcqqlTUWJUamqWMfjfohnEuxvEUlDpibEzeeJCiBLZsTsSOWREaSIJbInRfSdUGxheWVycw==')).LocalPlayer.startevent
Event:FireServer(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('KDQqAHcPpvhruCKOONveRyrFGehcLKlDubgndzZoYVTtNcxVSkdvBMRLBVnuaNDLzXIwEKFkWpjrqhiQmoNgPkipEffkTgARdueakcdeKLiAgdYsdBzrPJWoaqsogVUCsjZCLOrXXdQZhsWeMOpEYHQdNgCXVKerzCzbTFORQPBauOsIidXNDLmVcUTODxaoDgSWvmMRc3Bpbg=='), VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('McofowUcjVUSCGmZOCPPJotwlJjYulPyHAcfcdkyIMlHwTJgmZBWbRNgAMZyWSxbpRdVlTflvOBshDUSLNIUxvTrhEIPCrVopKMqmOmhNdNAvvIZeeqYRmDExPZNkfRPZIXjSZqjWwsThqyYTtRhZSKsJobYnyJbaVQWwYAXflpCLbmwHqBvrkoisEuebYaZPrCGizMJa2c0'))
 wait(0.2)
 if game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('CiFwaysGGtLqFQcSzkTdXfjkxylJFeczdilKTrdwCHQTKfIaCQFSNsmPFpvPhZsvMHNPfMJpEFlzsDrKvScDOpMHgmZcAXKoDKhepduXuzIbeMCDghGfJFnASEBqEDeuUGoBMYirgpweMucbMwOwmUXYHdLrIidlpRlBUdLvdvmUlTxZuAVIXFZSRSbmrNfLtAVnsvcfUGxheWVycw==')).LocalPlayer.statz.main.kg1.Value == _genkai
or game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('AeAPBVUZrRQUAzYXdNZEaOFumuAwVKtnrrVYvDvrAFkdkEJhSaeLlnmMrrrMLMKTjUHGZmdtGgqNjsaDMDlLiHIQkMEhxygMPnIYqGRpeisvxXRNcfMYDkMZQImrDoRDeKZjHEPdQMVhippuucvqLmvNqPeWsEXtFnnIbRukYHgcDpgGKxiOMJqSqACoiTqGpmzQolACUGxheWVycw==')).LocalPlayer.statz.main.kg2.Value == _genkai
or game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('cCZsXgBhlLSyCgcZLuUSlAtVDRUukrNjmWNqUjJZXZTviIMvHiwOFpVLlhMhLkmIIeSYbWvmwiRvbqdJLZVtBOksoEkfwCIFrmDKgUQfZpeKMAQMCoOIbbhDKlrJTuxxdvZdsgbFdOayqWxQajmnykmtHpVbQxQSPxukBMNAjWaAEpXlvClnsJetpvCjhPNAwCyFDCpQUGxheWVycw==')).LocalPlayer.statz.main.kg3.Value == _genkai
or game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('iWQoxxnDuDPhhxeVsWgpknmhxWBLQnWiBHWRLdxZgphISuqquMeWBLUYRjdWZodkAWTPourZCunBznxtAbdzZlcXtMiTPivUcKUqwkSKmxDpiXPaRLoPuRlZyAGCQbKFrcpMyUKZWQcQqSGIIoVkPJcUnebojtMoOpevfopFJOvbbYaXqCdaGBqcQAMCxYiiqpXbRNDTUGxheWVycw==')).LocalPlayer.statz.main.kg4.Value == _genkai
 then _G.Autokg = false
wait(0.1)
end

if game.Players.LocalPlayer.statz.spins.Value == 0 then
game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('ROKqTULqYkcjQZquksWRIodBarpJPptqxhMWFNCkpxwAIDrvMJVxKlbdRBGyrLxPhopLSymtMYrImzPdZDNYDEkDvVxzIJurxmVPOELaYfFPnVqOcMVVTUVQDrkTSztmcfYNdOVyekvNgKimRXrTSGGCYxKomXzfZXNwazvPYEsMdvTRpgSJBtBBXuEGdjFvPpsuYorRUGxheWVycw==')).LocalPlayer.startevent:FireServer(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('uekwOFiPCMNjgflzKwlWbcUTYioQLXKAZZEbEhVMzvgWwxqFyINjNdVINbnXCCfjkUVPklWDqKFnOKVmkKEQCGHISnDtJAZklSSlRKYLOmXQvvqjLOgvBXMoNKQHrzKrOUwXXegTrArPWEyGLjHZitUOMKprPdmVQCZjWffLASZungQQOROqksAZkbhBYKkKWBtvGTdtYmFuZA=='), VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('kkKJgYXQYHBmILywVVMzNoXmLlaAeIUtELXieFNqBzoALKXZBLhNjBEPkdmsZUeXOfGcacUUHaOadhesBGMHMlGNNCRHWgMxaSmraiyhgWFywEKQPgPSlAdstSetdGzvArgfwToJYkBrijBPKsJYxPINzGsFpgAFzCJhTWCqIzKpEjvKBdQhglAoNAQAdkzLyDsrpsJdXDEyOA=='))
game:GetService(VWCXVRYlloePtliizhpqumSdgMXYiJsOshgRdrNOcejPwoYztXiyXOBghwfbCeKBXAnoKtVAdkFYi('dgjeMtGkgcJayWqYPohGcdRWDJcNaxYLitvTlmhAQfgFCilSiAVPAGWfrZNALdRWsdOVTkernLEATJCgNuoGTMoMoYILRNtzpishbSUzhyCgLdzUTIiPRicLjoAMWTGOCGHugTLMAMMUczBdjrZWTyyJoQbazGynwWjQQOIQtRJsRBOxIwoyWuxRHfYZlcEHnrVxmzBwVGVsZXBvcnRTZXJ2aWNl')):Teleport(4616652839)
wait(0.1)

end
end    
